version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_project3
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_PERSONALIZATION_ENABLED=true
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=72

    volumes:
      - ./n8n_runtime:/home/node/.n8n   # 내부 데이터 유지
      - ./workflows:/workflows          # Git 관리 대상
